// AUTO-GENERATED by bo/t3_prism_sobol_batch.py — do not hand-edit.
// Preview wrapper for the T3-prism Sobol batch: imports the
// per-specimen STLs rendered from cad/t3-prism/t3-prism.scad
// (latest captive-core joints + A3 igloo top mounts + beside-
// mounted flat bottom key-seats), each projected onto the
// constant-mass manifold (PR #35 comment 5132975378).
// Plate: 350 x 320 mm (Bambu Lab H2D).
// Grid : 3 x 3 (cell 97.1 mm).
part = "all";  // "all" | "struts" | "cables"

if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec00-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec00-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec01-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec01-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec02-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec02-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec03-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec03-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec04-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec04-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec05-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec05-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec06-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec06-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec07-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec07-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round1-spec08-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round1-spec08-cables.stl");

// Visual marker for the IDEX prime/flush-tower reserve zone.
if (part == "all") {
  translate([305.00, 5.00, 0])
    cube([40.00, 310.00, 0.2]);
}
