// AUTO-GENERATED by bo/t3_prism_printed_mass_plate.py. Do not hand-edit.
// Preview wrapper for a constant-printed-mass batch: imports the
// per-specimen STLs rendered from cad/t3-prism/t3-prism.scad at the
// scale solved by bo/t3_prism_bo_campaign.py (constant printed grams).
// Plate: 350 x 320 mm (Bambu Lab H2D). Grid: 3 x 3.
part = "all";  // "all" | "struts" | "cables"

if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t37-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t37-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t38-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t38-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t39-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t39-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t40-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t40-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t41-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t41-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t42-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t42-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t43-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t43-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t44-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t44-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round4-t45-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round4-t45-cables.stl");

// Visual marker for the IDEX prime/flush-tower reserve zone.
if (part == "all") {
  translate([305.00, 5.00, 0])
    cube([40.00, 310.00, 0.2]);
}
