// AUTO-GENERATED by bo/t3_prism_sobol_batch.py — do not hand-edit.
// Single-batch Sobol design set for the T3-prism BO campaign
// (PR #35 comment 4503109338). All specimens vertically oriented
// (load axis = z). Supports will be manually painted in Bambu
// Studio per @achris0520's tip in PR #35 comment 4502140147.
// Plate: 350 x 320 mm (Bambu Lab H2D).
// Grid : 3 x 2 (cell 101.9 x 101.9 mm).
//
// `part` selects which half of each specimen to emit, mirroring
// `cad/t3-prism/t3-prism.scad`:
//   "all"    -> struts + cables fused (preview / single-material)
//   "struts" -> rigid skeleton + joint spheres (PLA / extruder 1)
//   "cables" -> tension members only (TPU / extruder 2)
// Override at the CLI with `-D 'part="struts"'`.
part = "all";  // "all" | "struts" | "cables"

// specimen 00  R=32.13 H=89.63 twist=59.78 strut_d=7.88 cable_d=5.39
// Captive-core joint params (mirror cad/t3-prism/t3-prism.scad,
// PR #35 comment 4511036510): bore = cable_d + 2*0.4 mm; core_od >= bore +
// 2*1.5 mm so the captive TPU mass cannot back out the bore; shell_id =
// core_od + 2*0.5 mm radial print-in-place clearance; shell_od =
// shell_id + 2*1.6 mm PLA wall (lifted to >= joint_d so the joint is
// never smaller than the legacy design).
S00_BORE_D    = 5.3902 + 2*0.4;
S00_CORE_OD   = max(S00_BORE_D + 2*1.5, 7.0000);
S00_SHELL_ID  = S00_CORE_OD + 2*0.5;
S00_SHELL_OD  = max(S00_SHELL_ID + 2*1.6, 7.0000);
S00_TEARDROP  = 7.8831 * 1.10;
module specimen_00_member(p1, p2, d) {
    v=p2-p1; L=norm(v);
    yaw=atan2(v[1],v[0]);
    pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
    translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
        cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
    }
}
module specimen_00_bore(dir, d, len) {
    yaw=atan2(dir[1],dir[0]);
    pitch=atan2(sqrt(dir[0]*dir[0]+dir[1]*dir[1]),dir[2]);
    rotate([0,0,yaw]) rotate([0,pitch,0]) translate([0,0,-len/2])
        cylinder(h=len, d=d);
}
function specimen_00_bp(i) = [32.1266*cos(90+120*i), 32.1266*sin(90+120*i), 0];
function specimen_00_tp(i) = [32.1266*cos(90+120*i+59.7792),
                                     32.1266*sin(90+120*i+59.7792), 89.6262];
function specimen_00_unit(v) = v / norm(v);
function specimen_00_sdir_b(i) =
    specimen_00_unit(specimen_00_tp(i) - specimen_00_bp(i));
function specimen_00_sdir_t(i) =
    specimen_00_unit(specimen_00_bp(i) - specimen_00_tp(i));
function specimen_00_cdirs_b(i) = [
    specimen_00_unit(specimen_00_bp((i+1)%3) - specimen_00_bp(i)),
    specimen_00_unit(specimen_00_bp((i+2)%3) - specimen_00_bp(i)),
    specimen_00_unit(specimen_00_tp((i+2)%3) - specimen_00_bp(i)),
];
function specimen_00_cdirs_t(i) = [
    specimen_00_unit(specimen_00_tp((i+1)%3) - specimen_00_tp(i)),
    specimen_00_unit(specimen_00_tp((i+2)%3) - specimen_00_tp(i)),
    specimen_00_unit(specimen_00_bp((i+1)%3) - specimen_00_tp(i)),
];
module specimen_00_shell(V, sdir, cdirs) {
    translate(V) difference() {
        hull() {
            sphere(d=S00_SHELL_OD);
            translate(sdir * (S00_SHELL_OD/2 + 1.5))
                sphere(d=S00_TEARDROP);
        }
        sphere(d=S00_SHELL_ID);
        for (cd = cdirs)
            specimen_00_bore(cd, S00_BORE_D, S00_SHELL_OD*2);
    }
}
module specimen_00_struts() {
    union() {
        for (i=[0:2]) {
            specimen_00_shell(specimen_00_bp(i),
                                     specimen_00_sdir_b(i),
                                     specimen_00_cdirs_b(i));
            specimen_00_shell(specimen_00_tp(i),
                                     specimen_00_sdir_t(i),
                                     specimen_00_cdirs_t(i));
            specimen_00_member(specimen_00_bp(i),
                                     specimen_00_tp(i), 7.8831);
        }
    }
}
module specimen_00_cables() {
    union() {
        for (i=[0:2]) {
            specimen_00_member(specimen_00_bp(i),
                                     specimen_00_bp((i+1)%3), 5.3902);
            specimen_00_member(specimen_00_tp(i),
                                     specimen_00_tp((i+1)%3), 5.3902);
            specimen_00_member(specimen_00_bp((i+1)%3),
                                     specimen_00_tp(i),       5.3902);
            // Captive TPU cores inside each PLA shell cavity.
            translate(specimen_00_bp(i)) sphere(d=S00_CORE_OD);
            translate(specimen_00_tp(i)) sphere(d=S00_CORE_OD);
        }
        // Bounding-box z-anchor so cables.stl inherits the struts.stl
        // world-Z extents (fixes the "cables too low" misalignment;
        // see cad/t3-prism/t3-prism.scad cables_z_anchor()).
        translate([0, 0, -S00_SHELL_OD/2])
            cube([0.005, 0.005, 89.6262 + S00_SHELL_OD], center=false);
    }
}
module specimen_00() {
    if      (part == "struts") specimen_00_struts();
    else if (part == "cables") specimen_00_cables();
    else union() { specimen_00_struts(); specimen_00_cables(); }
}
translate([89.071, 58.143, 6.695]) specimen_00();
// specimen 01  R=33.78 H=80.08 twist=77.41 strut_d=10.87 cable_d=3.00
// Captive-core joint params (mirror cad/t3-prism/t3-prism.scad,
// PR #35 comment 4511036510): bore = cable_d + 2*0.4 mm; core_od >= bore +
// 2*1.5 mm so the captive TPU mass cannot back out the bore; shell_id =
// core_od + 2*0.5 mm radial print-in-place clearance; shell_od =
// shell_id + 2*1.6 mm PLA wall (lifted to >= joint_d so the joint is
// never smaller than the legacy design).
S01_BORE_D    = 3.0003 + 2*0.4;
S01_CORE_OD   = max(S01_BORE_D + 2*1.5, 7.0000);
S01_SHELL_ID  = S01_CORE_OD + 2*0.5;
S01_SHELL_OD  = max(S01_SHELL_ID + 2*1.6, 7.0000);
S01_TEARDROP  = 10.8717 * 1.10;
module specimen_01_member(p1, p2, d) {
    v=p2-p1; L=norm(v);
    yaw=atan2(v[1],v[0]);
    pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
    translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
        cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
    }
}
module specimen_01_bore(dir, d, len) {
    yaw=atan2(dir[1],dir[0]);
    pitch=atan2(sqrt(dir[0]*dir[0]+dir[1]*dir[1]),dir[2]);
    rotate([0,0,yaw]) rotate([0,pitch,0]) translate([0,0,-len/2])
        cylinder(h=len, d=d);
}
function specimen_01_bp(i) = [33.7842*cos(90+120*i), 33.7842*sin(90+120*i), 0];
function specimen_01_tp(i) = [33.7842*cos(90+120*i+77.4080),
                                     33.7842*sin(90+120*i+77.4080), 80.0836];
function specimen_01_unit(v) = v / norm(v);
function specimen_01_sdir_b(i) =
    specimen_01_unit(specimen_01_tp(i) - specimen_01_bp(i));
function specimen_01_sdir_t(i) =
    specimen_01_unit(specimen_01_bp(i) - specimen_01_tp(i));
function specimen_01_cdirs_b(i) = [
    specimen_01_unit(specimen_01_bp((i+1)%3) - specimen_01_bp(i)),
    specimen_01_unit(specimen_01_bp((i+2)%3) - specimen_01_bp(i)),
    specimen_01_unit(specimen_01_tp((i+2)%3) - specimen_01_bp(i)),
];
function specimen_01_cdirs_t(i) = [
    specimen_01_unit(specimen_01_tp((i+1)%3) - specimen_01_tp(i)),
    specimen_01_unit(specimen_01_tp((i+2)%3) - specimen_01_tp(i)),
    specimen_01_unit(specimen_01_bp((i+1)%3) - specimen_01_tp(i)),
];
module specimen_01_shell(V, sdir, cdirs) {
    translate(V) difference() {
        hull() {
            sphere(d=S01_SHELL_OD);
            translate(sdir * (S01_SHELL_OD/2 + 1.5))
                sphere(d=S01_TEARDROP);
        }
        sphere(d=S01_SHELL_ID);
        for (cd = cdirs)
            specimen_01_bore(cd, S01_BORE_D, S01_SHELL_OD*2);
    }
}
module specimen_01_struts() {
    union() {
        for (i=[0:2]) {
            specimen_01_shell(specimen_01_bp(i),
                                     specimen_01_sdir_b(i),
                                     specimen_01_cdirs_b(i));
            specimen_01_shell(specimen_01_tp(i),
                                     specimen_01_sdir_t(i),
                                     specimen_01_cdirs_t(i));
            specimen_01_member(specimen_01_bp(i),
                                     specimen_01_tp(i), 10.8717);
        }
    }
}
module specimen_01_cables() {
    union() {
        for (i=[0:2]) {
            specimen_01_member(specimen_01_bp(i),
                                     specimen_01_bp((i+1)%3), 3.0003);
            specimen_01_member(specimen_01_tp(i),
                                     specimen_01_tp((i+1)%3), 3.0003);
            specimen_01_member(specimen_01_bp((i+1)%3),
                                     specimen_01_tp(i),       3.0003);
            // Captive TPU cores inside each PLA shell cavity.
            translate(specimen_01_bp(i)) sphere(d=S01_CORE_OD);
            translate(specimen_01_tp(i)) sphere(d=S01_CORE_OD);
        }
        // Bounding-box z-anchor so cables.stl inherits the struts.stl
        // world-Z extents (fixes the "cables too low" misalignment;
        // see cad/t3-prism/t3-prism.scad cables_z_anchor()).
        translate([0, 0, -S01_SHELL_OD/2])
            cube([0.005, 0.005, 80.0836 + S01_SHELL_OD], center=false);
    }
}
module specimen_01() {
    if      (part == "struts") specimen_01_struts();
    else if (part == "cables") specimen_01_cables();
    else union() { specimen_01_struts(); specimen_01_cables(); }
}
translate([190.929, 58.143, 6.695]) specimen_01();
// specimen 02  R=38.97 H=99.99 twist=47.69 strut_d=7.07 cable_d=3.92
// Captive-core joint params (mirror cad/t3-prism/t3-prism.scad,
// PR #35 comment 4511036510): bore = cable_d + 2*0.4 mm; core_od >= bore +
// 2*1.5 mm so the captive TPU mass cannot back out the bore; shell_id =
// core_od + 2*0.5 mm radial print-in-place clearance; shell_od =
// shell_id + 2*1.6 mm PLA wall (lifted to >= joint_d so the joint is
// never smaller than the legacy design).
S02_BORE_D    = 3.9241 + 2*0.4;
S02_CORE_OD   = max(S02_BORE_D + 2*1.5, 7.0000);
S02_SHELL_ID  = S02_CORE_OD + 2*0.5;
S02_SHELL_OD  = max(S02_SHELL_ID + 2*1.6, 7.0000);
S02_TEARDROP  = 7.0737 * 1.10;
module specimen_02_member(p1, p2, d) {
    v=p2-p1; L=norm(v);
    yaw=atan2(v[1],v[0]);
    pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
    translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
        cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
    }
}
module specimen_02_bore(dir, d, len) {
    yaw=atan2(dir[1],dir[0]);
    pitch=atan2(sqrt(dir[0]*dir[0]+dir[1]*dir[1]),dir[2]);
    rotate([0,0,yaw]) rotate([0,pitch,0]) translate([0,0,-len/2])
        cylinder(h=len, d=d);
}
function specimen_02_bp(i) = [38.9665*cos(90+120*i), 38.9665*sin(90+120*i), 0];
function specimen_02_tp(i) = [38.9665*cos(90+120*i+47.6915),
                                     38.9665*sin(90+120*i+47.6915), 99.9950];
function specimen_02_unit(v) = v / norm(v);
function specimen_02_sdir_b(i) =
    specimen_02_unit(specimen_02_tp(i) - specimen_02_bp(i));
function specimen_02_sdir_t(i) =
    specimen_02_unit(specimen_02_bp(i) - specimen_02_tp(i));
function specimen_02_cdirs_b(i) = [
    specimen_02_unit(specimen_02_bp((i+1)%3) - specimen_02_bp(i)),
    specimen_02_unit(specimen_02_bp((i+2)%3) - specimen_02_bp(i)),
    specimen_02_unit(specimen_02_tp((i+2)%3) - specimen_02_bp(i)),
];
function specimen_02_cdirs_t(i) = [
    specimen_02_unit(specimen_02_tp((i+1)%3) - specimen_02_tp(i)),
    specimen_02_unit(specimen_02_tp((i+2)%3) - specimen_02_tp(i)),
    specimen_02_unit(specimen_02_bp((i+1)%3) - specimen_02_tp(i)),
];
module specimen_02_shell(V, sdir, cdirs) {
    translate(V) difference() {
        hull() {
            sphere(d=S02_SHELL_OD);
            translate(sdir * (S02_SHELL_OD/2 + 1.5))
                sphere(d=S02_TEARDROP);
        }
        sphere(d=S02_SHELL_ID);
        for (cd = cdirs)
            specimen_02_bore(cd, S02_BORE_D, S02_SHELL_OD*2);
    }
}
module specimen_02_struts() {
    union() {
        for (i=[0:2]) {
            specimen_02_shell(specimen_02_bp(i),
                                     specimen_02_sdir_b(i),
                                     specimen_02_cdirs_b(i));
            specimen_02_shell(specimen_02_tp(i),
                                     specimen_02_sdir_t(i),
                                     specimen_02_cdirs_t(i));
            specimen_02_member(specimen_02_bp(i),
                                     specimen_02_tp(i), 7.0737);
        }
    }
}
module specimen_02_cables() {
    union() {
        for (i=[0:2]) {
            specimen_02_member(specimen_02_bp(i),
                                     specimen_02_bp((i+1)%3), 3.9241);
            specimen_02_member(specimen_02_tp(i),
                                     specimen_02_tp((i+1)%3), 3.9241);
            specimen_02_member(specimen_02_bp((i+1)%3),
                                     specimen_02_tp(i),       3.9241);
            // Captive TPU cores inside each PLA shell cavity.
            translate(specimen_02_bp(i)) sphere(d=S02_CORE_OD);
            translate(specimen_02_tp(i)) sphere(d=S02_CORE_OD);
        }
        // Bounding-box z-anchor so cables.stl inherits the struts.stl
        // world-Z extents (fixes the "cables too low" misalignment;
        // see cad/t3-prism/t3-prism.scad cables_z_anchor()).
        translate([0, 0, -S02_SHELL_OD/2])
            cube([0.005, 0.005, 99.9950 + S02_SHELL_OD], center=false);
    }
}
module specimen_02() {
    if      (part == "struts") specimen_02_struts();
    else if (part == "cables") specimen_02_cables();
    else union() { specimen_02_struts(); specimen_02_cables(); }
}
translate([89.071, 160.000, 6.695]) specimen_02();
// specimen 03  R=25.12 H=72.06 twist=65.12 strut_d=10.18 cable_d=4.66
// Captive-core joint params (mirror cad/t3-prism/t3-prism.scad,
// PR #35 comment 4511036510): bore = cable_d + 2*0.4 mm; core_od >= bore +
// 2*1.5 mm so the captive TPU mass cannot back out the bore; shell_id =
// core_od + 2*0.5 mm radial print-in-place clearance; shell_od =
// shell_id + 2*1.6 mm PLA wall (lifted to >= joint_d so the joint is
// never smaller than the legacy design).
S03_BORE_D    = 4.6640 + 2*0.4;
S03_CORE_OD   = max(S03_BORE_D + 2*1.5, 7.0000);
S03_SHELL_ID  = S03_CORE_OD + 2*0.5;
S03_SHELL_OD  = max(S03_SHELL_ID + 2*1.6, 7.0000);
S03_TEARDROP  = 10.1789 * 1.10;
module specimen_03_member(p1, p2, d) {
    v=p2-p1; L=norm(v);
    yaw=atan2(v[1],v[0]);
    pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
    translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
        cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
    }
}
module specimen_03_bore(dir, d, len) {
    yaw=atan2(dir[1],dir[0]);
    pitch=atan2(sqrt(dir[0]*dir[0]+dir[1]*dir[1]),dir[2]);
    rotate([0,0,yaw]) rotate([0,pitch,0]) translate([0,0,-len/2])
        cylinder(h=len, d=d);
}
function specimen_03_bp(i) = [25.1224*cos(90+120*i), 25.1224*sin(90+120*i), 0];
function specimen_03_tp(i) = [25.1224*cos(90+120*i+65.1213),
                                     25.1224*sin(90+120*i+65.1213), 72.0587];
function specimen_03_unit(v) = v / norm(v);
function specimen_03_sdir_b(i) =
    specimen_03_unit(specimen_03_tp(i) - specimen_03_bp(i));
function specimen_03_sdir_t(i) =
    specimen_03_unit(specimen_03_bp(i) - specimen_03_tp(i));
function specimen_03_cdirs_b(i) = [
    specimen_03_unit(specimen_03_bp((i+1)%3) - specimen_03_bp(i)),
    specimen_03_unit(specimen_03_bp((i+2)%3) - specimen_03_bp(i)),
    specimen_03_unit(specimen_03_tp((i+2)%3) - specimen_03_bp(i)),
];
function specimen_03_cdirs_t(i) = [
    specimen_03_unit(specimen_03_tp((i+1)%3) - specimen_03_tp(i)),
    specimen_03_unit(specimen_03_tp((i+2)%3) - specimen_03_tp(i)),
    specimen_03_unit(specimen_03_bp((i+1)%3) - specimen_03_tp(i)),
];
module specimen_03_shell(V, sdir, cdirs) {
    translate(V) difference() {
        hull() {
            sphere(d=S03_SHELL_OD);
            translate(sdir * (S03_SHELL_OD/2 + 1.5))
                sphere(d=S03_TEARDROP);
        }
        sphere(d=S03_SHELL_ID);
        for (cd = cdirs)
            specimen_03_bore(cd, S03_BORE_D, S03_SHELL_OD*2);
    }
}
module specimen_03_struts() {
    union() {
        for (i=[0:2]) {
            specimen_03_shell(specimen_03_bp(i),
                                     specimen_03_sdir_b(i),
                                     specimen_03_cdirs_b(i));
            specimen_03_shell(specimen_03_tp(i),
                                     specimen_03_sdir_t(i),
                                     specimen_03_cdirs_t(i));
            specimen_03_member(specimen_03_bp(i),
                                     specimen_03_tp(i), 10.1789);
        }
    }
}
module specimen_03_cables() {
    union() {
        for (i=[0:2]) {
            specimen_03_member(specimen_03_bp(i),
                                     specimen_03_bp((i+1)%3), 4.6640);
            specimen_03_member(specimen_03_tp(i),
                                     specimen_03_tp((i+1)%3), 4.6640);
            specimen_03_member(specimen_03_bp((i+1)%3),
                                     specimen_03_tp(i),       4.6640);
            // Captive TPU cores inside each PLA shell cavity.
            translate(specimen_03_bp(i)) sphere(d=S03_CORE_OD);
            translate(specimen_03_tp(i)) sphere(d=S03_CORE_OD);
        }
        // Bounding-box z-anchor so cables.stl inherits the struts.stl
        // world-Z extents (fixes the "cables too low" misalignment;
        // see cad/t3-prism/t3-prism.scad cables_z_anchor()).
        translate([0, 0, -S03_SHELL_OD/2])
            cube([0.005, 0.005, 72.0587 + S03_SHELL_OD], center=false);
    }
}
module specimen_03() {
    if      (part == "struts") specimen_03_struts();
    else if (part == "cables") specimen_03_cables();
    else union() { specimen_03_struts(); specimen_03_cables(); }
}
translate([190.929, 160.000, 6.695]) specimen_03();
// specimen 04  R=27.61 H=104.13 twist=70.44 strut_d=9.28 cable_d=4.49
// Captive-core joint params (mirror cad/t3-prism/t3-prism.scad,
// PR #35 comment 4511036510): bore = cable_d + 2*0.4 mm; core_od >= bore +
// 2*1.5 mm so the captive TPU mass cannot back out the bore; shell_id =
// core_od + 2*0.5 mm radial print-in-place clearance; shell_od =
// shell_id + 2*1.6 mm PLA wall (lifted to >= joint_d so the joint is
// never smaller than the legacy design).
S04_BORE_D    = 4.4922 + 2*0.4;
S04_CORE_OD   = max(S04_BORE_D + 2*1.5, 7.0000);
S04_SHELL_ID  = S04_CORE_OD + 2*0.5;
S04_SHELL_OD  = max(S04_SHELL_ID + 2*1.6, 7.0000);
S04_TEARDROP  = 9.2816 * 1.10;
module specimen_04_member(p1, p2, d) {
    v=p2-p1; L=norm(v);
    yaw=atan2(v[1],v[0]);
    pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
    translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
        cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
    }
}
module specimen_04_bore(dir, d, len) {
    yaw=atan2(dir[1],dir[0]);
    pitch=atan2(sqrt(dir[0]*dir[0]+dir[1]*dir[1]),dir[2]);
    rotate([0,0,yaw]) rotate([0,pitch,0]) translate([0,0,-len/2])
        cylinder(h=len, d=d);
}
function specimen_04_bp(i) = [27.6114*cos(90+120*i), 27.6114*sin(90+120*i), 0];
function specimen_04_tp(i) = [27.6114*cos(90+120*i+70.4432),
                                     27.6114*sin(90+120*i+70.4432), 104.1304];
function specimen_04_unit(v) = v / norm(v);
function specimen_04_sdir_b(i) =
    specimen_04_unit(specimen_04_tp(i) - specimen_04_bp(i));
function specimen_04_sdir_t(i) =
    specimen_04_unit(specimen_04_bp(i) - specimen_04_tp(i));
function specimen_04_cdirs_b(i) = [
    specimen_04_unit(specimen_04_bp((i+1)%3) - specimen_04_bp(i)),
    specimen_04_unit(specimen_04_bp((i+2)%3) - specimen_04_bp(i)),
    specimen_04_unit(specimen_04_tp((i+2)%3) - specimen_04_bp(i)),
];
function specimen_04_cdirs_t(i) = [
    specimen_04_unit(specimen_04_tp((i+1)%3) - specimen_04_tp(i)),
    specimen_04_unit(specimen_04_tp((i+2)%3) - specimen_04_tp(i)),
    specimen_04_unit(specimen_04_bp((i+1)%3) - specimen_04_tp(i)),
];
module specimen_04_shell(V, sdir, cdirs) {
    translate(V) difference() {
        hull() {
            sphere(d=S04_SHELL_OD);
            translate(sdir * (S04_SHELL_OD/2 + 1.5))
                sphere(d=S04_TEARDROP);
        }
        sphere(d=S04_SHELL_ID);
        for (cd = cdirs)
            specimen_04_bore(cd, S04_BORE_D, S04_SHELL_OD*2);
    }
}
module specimen_04_struts() {
    union() {
        for (i=[0:2]) {
            specimen_04_shell(specimen_04_bp(i),
                                     specimen_04_sdir_b(i),
                                     specimen_04_cdirs_b(i));
            specimen_04_shell(specimen_04_tp(i),
                                     specimen_04_sdir_t(i),
                                     specimen_04_cdirs_t(i));
            specimen_04_member(specimen_04_bp(i),
                                     specimen_04_tp(i), 9.2816);
        }
    }
}
module specimen_04_cables() {
    union() {
        for (i=[0:2]) {
            specimen_04_member(specimen_04_bp(i),
                                     specimen_04_bp((i+1)%3), 4.4922);
            specimen_04_member(specimen_04_tp(i),
                                     specimen_04_tp((i+1)%3), 4.4922);
            specimen_04_member(specimen_04_bp((i+1)%3),
                                     specimen_04_tp(i),       4.4922);
            // Captive TPU cores inside each PLA shell cavity.
            translate(specimen_04_bp(i)) sphere(d=S04_CORE_OD);
            translate(specimen_04_tp(i)) sphere(d=S04_CORE_OD);
        }
        // Bounding-box z-anchor so cables.stl inherits the struts.stl
        // world-Z extents (fixes the "cables too low" misalignment;
        // see cad/t3-prism/t3-prism.scad cables_z_anchor()).
        translate([0, 0, -S04_SHELL_OD/2])
            cube([0.005, 0.005, 104.1304 + S04_SHELL_OD], center=false);
    }
}
module specimen_04() {
    if      (part == "struts") specimen_04_struts();
    else if (part == "cables") specimen_04_cables();
    else union() { specimen_04_struts(); specimen_04_cables(); }
}
translate([89.071, 261.857, 6.695]) specimen_04();
// specimen 05  R=36.30 H=63.23 twist=52.99 strut_d=6.46 cable_d=4.06
// Captive-core joint params (mirror cad/t3-prism/t3-prism.scad,
// PR #35 comment 4511036510): bore = cable_d + 2*0.4 mm; core_od >= bore +
// 2*1.5 mm so the captive TPU mass cannot back out the bore; shell_id =
// core_od + 2*0.5 mm radial print-in-place clearance; shell_od =
// shell_id + 2*1.6 mm PLA wall (lifted to >= joint_d so the joint is
// never smaller than the legacy design).
S05_BORE_D    = 4.0550 + 2*0.4;
S05_CORE_OD   = max(S05_BORE_D + 2*1.5, 7.0000);
S05_SHELL_ID  = S05_CORE_OD + 2*0.5;
S05_SHELL_OD  = max(S05_SHELL_ID + 2*1.6, 7.0000);
S05_TEARDROP  = 6.4571 * 1.10;
module specimen_05_member(p1, p2, d) {
    v=p2-p1; L=norm(v);
    yaw=atan2(v[1],v[0]);
    pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
    translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
        cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
    }
}
module specimen_05_bore(dir, d, len) {
    yaw=atan2(dir[1],dir[0]);
    pitch=atan2(sqrt(dir[0]*dir[0]+dir[1]*dir[1]),dir[2]);
    rotate([0,0,yaw]) rotate([0,pitch,0]) translate([0,0,-len/2])
        cylinder(h=len, d=d);
}
function specimen_05_bp(i) = [36.3001*cos(90+120*i), 36.3001*sin(90+120*i), 0];
function specimen_05_tp(i) = [36.3001*cos(90+120*i+52.9940),
                                     36.3001*sin(90+120*i+52.9940), 63.2297];
function specimen_05_unit(v) = v / norm(v);
function specimen_05_sdir_b(i) =
    specimen_05_unit(specimen_05_tp(i) - specimen_05_bp(i));
function specimen_05_sdir_t(i) =
    specimen_05_unit(specimen_05_bp(i) - specimen_05_tp(i));
function specimen_05_cdirs_b(i) = [
    specimen_05_unit(specimen_05_bp((i+1)%3) - specimen_05_bp(i)),
    specimen_05_unit(specimen_05_bp((i+2)%3) - specimen_05_bp(i)),
    specimen_05_unit(specimen_05_tp((i+2)%3) - specimen_05_bp(i)),
];
function specimen_05_cdirs_t(i) = [
    specimen_05_unit(specimen_05_tp((i+1)%3) - specimen_05_tp(i)),
    specimen_05_unit(specimen_05_tp((i+2)%3) - specimen_05_tp(i)),
    specimen_05_unit(specimen_05_bp((i+1)%3) - specimen_05_tp(i)),
];
module specimen_05_shell(V, sdir, cdirs) {
    translate(V) difference() {
        hull() {
            sphere(d=S05_SHELL_OD);
            translate(sdir * (S05_SHELL_OD/2 + 1.5))
                sphere(d=S05_TEARDROP);
        }
        sphere(d=S05_SHELL_ID);
        for (cd = cdirs)
            specimen_05_bore(cd, S05_BORE_D, S05_SHELL_OD*2);
    }
}
module specimen_05_struts() {
    union() {
        for (i=[0:2]) {
            specimen_05_shell(specimen_05_bp(i),
                                     specimen_05_sdir_b(i),
                                     specimen_05_cdirs_b(i));
            specimen_05_shell(specimen_05_tp(i),
                                     specimen_05_sdir_t(i),
                                     specimen_05_cdirs_t(i));
            specimen_05_member(specimen_05_bp(i),
                                     specimen_05_tp(i), 6.4571);
        }
    }
}
module specimen_05_cables() {
    union() {
        for (i=[0:2]) {
            specimen_05_member(specimen_05_bp(i),
                                     specimen_05_bp((i+1)%3), 4.0550);
            specimen_05_member(specimen_05_tp(i),
                                     specimen_05_tp((i+1)%3), 4.0550);
            specimen_05_member(specimen_05_bp((i+1)%3),
                                     specimen_05_tp(i),       4.0550);
            // Captive TPU cores inside each PLA shell cavity.
            translate(specimen_05_bp(i)) sphere(d=S05_CORE_OD);
            translate(specimen_05_tp(i)) sphere(d=S05_CORE_OD);
        }
        // Bounding-box z-anchor so cables.stl inherits the struts.stl
        // world-Z extents (fixes the "cables too low" misalignment;
        // see cad/t3-prism/t3-prism.scad cables_z_anchor()).
        translate([0, 0, -S05_SHELL_OD/2])
            cube([0.005, 0.005, 63.2297 + S05_SHELL_OD], center=false);
    }
}
module specimen_05() {
    if      (part == "struts") specimen_05_struts();
    else if (part == "cables") specimen_05_cables();
    else union() { specimen_05_struts(); specimen_05_cables(); }
}
translate([190.929, 261.857, 6.695]) specimen_05();

// Visual marker for the IDEX prime/flush-tower reserve zone.
// 70 mm wide strip on the +X side of the
// plate is held back from the specimen grid so the slicer can
// drop a wipe tower there without colliding (PR #35 comment
// 4513164299).
if (part == "all") {
  translate([285.00, 5.00, 0])
    cube([60.00, 310.00, 0.2]);
}
