// AUTO-GENERATED by bo/t3_prism_printed_mass_plate.py. Do not hand-edit.
// Preview wrapper for a constant-printed-mass batch: imports the
// per-specimen STLs rendered from cad/t3-prism/t3-prism.scad at the
// scale solved by bo/t3_prism_bo_campaign.py (constant printed grams).
// Plate: 350 x 320 mm (Bambu Lab H2D). Grid: 3 x 3.
part = "all";  // "all" | "struts" | "cables"

if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t55-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t55-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t56-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t56-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t57-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t57-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t58-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t58-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t59-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t59-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t60-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t60-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t61-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t61-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t62-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t62-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t63-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t63-cables.stl");

// Visual marker for the IDEX prime/flush-tower reserve zone.
if (part == "all") {
  translate([305.00, 5.00, 0])
    cube([40.00, 310.00, 0.2]);
}
