// AUTO-GENERATED by bo/t3_prism_printed_mass_plate.py. Do not hand-edit.
// Preview wrapper for a constant-printed-mass batch: imports the
// per-specimen STLs rendered from cad/t3-prism/t3-prism.scad at the
// scale solved by bo/t3_prism_bo_campaign.py (constant printed grams).
// Plate: 350 x 320 mm (Bambu Lab H2D). Grid: 3 x 3.
part = "all";  // "all" | "struts" | "cables"

if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t28-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t28-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t29-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t29-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t30-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t30-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t31-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t31-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t32-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t32-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t33-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t33-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t34-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t34-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t35-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t35-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round3-t36-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round3-t36-cables.stl");

// Visual marker for the IDEX prime/flush-tower reserve zone.
if (part == "all") {
  translate([305.00, 5.00, 0])
    cube([40.00, 310.00, 0.2]);
}
