// AUTO-GENERATED by bo/t3_prism_sobol_batch.py — do not hand-edit.
// Single-batch Sobol design set for the T3-prism BO campaign
// (PR #35 comment 4503109338). All specimens vertically oriented
// (load axis = z). Supports will be manually painted in Bambu
// Studio per @achris0520's tip in PR #35 comment 4502140147.
// Plate: 350 x 320 mm (Bambu Lab H2D).
// Grid : 3 x 3 (cell 97.0 x 97.0 mm).

// specimen 00  R=32.13 H=89.63 twist=59.78 strut_d=7.88 cable_d=5.39
module specimen_00() {
    R=32.1266; H=89.6262; twist_=59.7792;
    strut_d=7.8831; cable_d=5.3902; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([77.993, 62.993, 3.500]) specimen_00();
// specimen 01  R=33.78 H=80.08 twist=77.41 strut_d=10.87 cable_d=3.00
module specimen_01() {
    R=33.7842; H=80.0836; twist_=77.4080;
    strut_d=10.8717; cable_d=3.0003; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([175.000, 62.993, 3.500]) specimen_01();
// specimen 02  R=38.97 H=99.99 twist=47.69 strut_d=7.07 cable_d=3.92
module specimen_02() {
    R=38.9665; H=99.9950; twist_=47.6915;
    strut_d=7.0737; cable_d=3.9241; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([272.007, 62.993, 3.500]) specimen_02();
// specimen 03  R=25.12 H=72.06 twist=65.12 strut_d=10.18 cable_d=4.66
module specimen_03() {
    R=25.1224; H=72.0587; twist_=65.1213;
    strut_d=10.1789; cable_d=4.6640; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([77.993, 160.000, 3.500]) specimen_03();
// specimen 04  R=27.61 H=104.13 twist=70.44 strut_d=9.28 cable_d=4.49
module specimen_04() {
    R=27.6114; H=104.1304; twist_=70.4432;
    strut_d=9.2816; cable_d=4.4922; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([175.000, 160.000, 3.500]) specimen_04();
// specimen 05  R=36.30 H=63.23 twist=52.99 strut_d=6.46 cable_d=4.06
module specimen_05() {
    R=36.3001; H=63.2297; twist_=52.9940;
    strut_d=6.4571; cable_d=4.0550; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([272.007, 160.000, 3.500]) specimen_05();
// specimen 06  R=35.98 H=96.45 twist=62.11 strut_d=11.66 cable_d=3.49
module specimen_06() {
    R=35.9821; H=96.4464; twist_=62.1055;
    strut_d=11.6620; cable_d=3.4949; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([77.993, 257.007, 3.500]) specimen_06();
// specimen 07  R=30.11 H=74.82 twist=44.46 strut_d=8.58 cable_d=4.94
module specimen_07() {
    R=30.1066; H=74.8199; twist_=44.4573;
    strut_d=8.5803; cable_d=4.9377; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([175.000, 257.007, 3.500]) specimen_07();
// specimen 08  R=29.02 H=100.87 twist=63.76 strut_d=6.20 cable_d=3.20
module specimen_08() {
    R=29.0207; H=100.8663; twist_=63.7624;
    strut_d=6.1990; cable_d=3.1969; joint_d=7.0000;
    module member_(p1,p2,d) {
        v=p2-p1; L=norm(v);
        yaw=atan2(v[1],v[0]);
        pitch=atan2(sqrt(v[0]*v[0]+v[1]*v[1]),v[2]);
        translate(p1) rotate([0,0,yaw]) rotate([0,pitch,0]) {
            cylinder(h=L,d=d); sphere(d=d); translate([0,0,L]) sphere(d=d);
        }
    }
    function bp(i)=[R*cos(90+120*i), R*sin(90+120*i), 0];
    function tp(i)=[R*cos(90+120*i+twist_), R*sin(90+120*i+twist_), H];
    union() {
        for (i=[0:2]) {
            translate(bp(i)) sphere(d=joint_d);
            translate(tp(i)) sphere(d=joint_d);
            member_(bp(i), tp(i), strut_d);
            member_(bp(i), bp((i+1)%3), cable_d);
            member_(tp(i), tp((i+1)%3), cable_d);
            member_(bp((i+1)%3), tp(i), cable_d);
        }
    }
}
translate([272.007, 257.007, 3.500]) specimen_08();
