// AUTO-GENERATED by bo/t3_prism_printed_mass_plate.py. Do not hand-edit.
// Preview wrapper for a constant-printed-mass batch: imports the
// per-specimen STLs rendered from cad/t3-prism/t3-prism.scad at the
// scale solved by bo/t3_prism_bo_campaign.py (constant printed grams).
// Plate: 350 x 320 mm (Bambu Lab H2D). Grid: 3 x 3.
part = "all";  // "all" | "struts" | "cables"

if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t46-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t46-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t47-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t47-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t48-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t48-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t49-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t49-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t50-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t50-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t51-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t51-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t52-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t52-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t53-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t53-cables.stl");
if (part == "all" || part == "struts")
    import("per-specimen-stls/t3-prism-bo-round5-t54-struts.stl");
if (part == "all" || part == "cables")
    import("per-specimen-stls/t3-prism-bo-round5-t54-cables.stl");

// Visual marker for the IDEX prime/flush-tower reserve zone.
if (part == "all") {
  translate([305.00, 5.00, 0])
    cube([40.00, 310.00, 0.2]);
}
